### ISSUE TITLE
Use CMake SHARED instead of MODULE

### ISSUE THREAD

**Issue by ice-phoenix** [dermesser/libsocket#29]
Specifying socket and socket++ to be of type MODULE makes it impossible to link with them via `target_link_libraries`.

**Comment by dermesser** [comment]
Which use case do you have for that -- are you including the libsocket CMake files in a project of yours? (my knowledge of CMake, which hasn't been good in the past, is even rustier now...)

The intention was to just produce the SOs, which can be linked against from anywhere. Also, I want to apologize about the month-long delay of my reply :-(

**Comment by ice-phoenix** [comment]
Taken from the CMake docs:

> SHARED libraries are linked dynamically and loaded at runtime. MODULE libraries are plugins that are not linked into other targets but may be loaded dynamically at runtime using dlopen-like functionality.

As I understand it, you're abusing the fact that regular Make allows one to actually link against MODULE library and that it kinda works =)

**Comment by dermesser** [comment]
#32 fixes this.
