### ISSUE TITLE
compilation error 

### ISSUE THREAD

**Issue by spatchola** [dermesser/libsocket#35]
## i use libsocket to compile another project but i have this error , what this is mean ?

/home/pi/libsocket/C++/streamclient.cpp:130: >>(std::string) input: Error while reading! (Connection reset by peer) 
errno code: 104Socket client closed the connection

**Comment by dermesser** [comment]
This is not a compilation error; it's ECONNRESET.

**Comment by spatchola** [comment]
what do you mean exactly in this case by ECONNRESET and how can i solve this problem ! i writed this in Google but i dn't find anything to help me :/

**Comment by dermesser** [comment]
ECONNRESET means that your remote end has reset the connection. It's not a compilation error.

**Comment by yisonPylkita** [comment]
Given your (@dermesser) answer, this issue seems to be solved

**Comment by dermesser** [comment]
this never was an issue ;-)
