### ISSUE TITLE
-O3 level optimization causes selectset.wait(n) to malfunction

### ISSUE THREAD

**Issue by dsorber** [dermesser/libsocket#37]
I'm using libsocket++ for a project and I noticed that when compiling my code with GCC's "-O3" optimization level selectset.wait(n), where n > 0, returns immediately even though both the read and write ready lists are empty.  When n=0 wait() behaves as expected.  When compiling with -O2 (or lower) and setting n > 0 wait() also behaves as expected.

I did a little digging and the problem appears to be caused by this, from select.hpp:

```
    template<typename SockT>
    typename selectset<SockT>::ready_socks selectset<SockT>::wait(long long microsecs)
    {
	int n = 0;

	struct timeval *timeout = NULL;

	if ( microsecs != 0 )
	{
            struct timeval _timeout;
	    timeout = &_timeout;

	    long long micropart = microsecs % 1000000;
	    long long secpart   = (microsecs - micropart) / 1000000;

	    _timeout.tv_sec  = secpart;
	    _timeout.tv_usec = microsecs;
	}

	n = select(highestfd(filedescriptors)+1,&readset,&writeset,NULL,timeout);
```

The `struct timeval _timeout` is declared inside the if block so it is scoped to that block.  Therefore I'm guessing that GCC's -O3 optimizations detect this strip out that entire if block.  The fix is trivial, of course, just move that declaration up outside of the if block.  I tried out the fix on my local copy and wait() now works correctly when compiled with -O3 and n > 0.

My system is running Ubuntu 14.04.5 with GCC 4.8.4

**Comment by dinarrow** [comment]
SNAP!! Just about to post the same bug. Should have fixed it yesterday when it first hit me:-)

In my case the issue became apparent when compiling and running on Android (same code on linux ran successfully).

This has nothing to do with your optimization, it is a coding error. The _timeout struct is constructed on the stack and has a life time of the if block. The timeout pointer continues to point to the stack memory which could be overwritten at any time. In your case -O3 cause it to happen, in my case the different platform.

Your solution is correct and should be applied in all cases.

Cheers

**Comment by dsorber** [comment]
True, this is a general coding error that should be fixed. I didn't mean to suggest otherwise.  In the -O2 (and lower) cases that if block is executed (and not stripped out) so `struct timeval _timeout` happens to still be on the stack since it hasn't been overwritten and therefore the code works but it is certainly not correct.

**Comment by dermesser** [comment]
Yes, that is a bug. Would you (any of you :) mind providing a pull request?

**Comment by dinarrow** [comment]
Will do as soon as a read up what and how :-) New to this cooperative programming lark. Probably later today if no one beats me to it.

**Comment by dermesser** [comment]
PR has been merged.
