### ISSUE TITLE
"Resource temporarily unavailable" when receiving with a non blocking inet_dgram_server socket

### ISSUE THREAD

**Issue by 1arthur1** [dermesser/libsocket#50]
Hi,

Here is the code:

```C++
libsocket::inet_dgram_server sock("localhost", "4000", LIBSOCKET_IPv4, SOCK_NONBLOCK);

if(sock.rcvfrom(ntwrk_buf, 1024, ntwrk_from, ntwrk_from_port) != -1)
{
    cout << "data received" << endl;
}
```

In the console it writes "Resource temporarily unavailable" when I launch this code. After some debugging, I found that this message is coming from check_error function called in recvfrom_inet_dgram_socket when recvfrom returns -1. But for a non blocking socket, it's not an issue, that's when we didn't receive any data.

I just deleted the call to check_error and the message is not shown anymore but I don't think that's the best thing to do. Did I miss something there to make a non blocking socket?

Thanks,

Arthur

**Comment by dermesser** [comment]
I think this is caused by me enabling debug_write() on errors accidentally: https://github.com/dermesser/libsocket/blame/master/CMakeLists.txt#L27

The commit just submitted should fix this.

**Comment by 1arthur1** [comment]
Yes that's a way to stop showing the message but check_error will still detects an error while it's not. Anyway, thanks for the commit, I'll be able to use your library without any change ;)

**Comment by dermesser** [comment]
It is an error, though, and it should be reported as such. recvfrom(2) returns -1 and sets errno to EAGAIN.

**Comment by 1arthur1** [comment]
You are right, my bad :)
