### ISSUE TITLE
memory leakage in create_unix_stream_socket

### ISSUE THREAD

**Issue by darktrial** [dermesser/libsocket#56]
After check the connection status in below code, the sfd variable needs to be freed.
`` if ( -1 == check_error(connect(sfd,(struct sockaddr*)&saddr,sizeof(saddr.sun_family) + strlen(saddr.sun_path)) ) )
return -1;``

The code should be changed as below.

`` if ( -1 == check_error(connect(sfd,(struct sockaddr*)&saddr,sizeof(saddr.sun_family) + strlen(saddr.sun_path)) ) )
{
close(sfd);
return -1;
}``

**Comment by dermesser** [comment]
Thank you for the report!
