### ISSUE TITLE
Letting you know about a new (partial) platform

### ISSUE THREAD

**Issue by sjaymin1001** [dermesser/libsocket#62]
@dermesser 

Hey there,

I have been using libsocket successfully in my project on Android OS. Although I'm only using Unix domain sockets and other parts are removed, you may mention this in your official documents.

My stripped version of libsocket for Android with build script working with Android NDK is available at: https://github.com/sjaymin1001/libsocket. Have a look!

**Comment by dermesser** [comment]
Thank you! :)
