### ISSUE TITLE
bug for epollset

### ISSUE THREAD

**Issue by ancloud-teach** [dermesser/libsocket#65]
in the epollset constructor,  it create the epollfd.
`epollfd = epoll_create1(0);`
but in the destructor, it don't close it.
template <typename SocketT>
```
epollset<SocketT>::~epollset(void) {
    close(epollfd);  /* add close the epollfd */
    delete[] events;
}
```

**Comment by dermesser** [comment]
yes! you're right. Thank you for the find! Awkward that this has escaped me for so long :)
